CREATE SCHEMA mpeix;

CREATE USER mpeix WITH ENCRYPTED PASSWORD 'mpeix';
-- ALTER USER mpeix WITH PASSWORD 'mpeix';

GRANT USAGE ON SCHEMA mpeix TO mpeix;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mpeix TO mpeix;
