openapi: 3.0.0
info:
  description: Mpeix microservice responsible for the schedule
  version: "1.0.0"
  title: Schedule
  contact:
    name: Kekmech
    url: https://vk.com/kekmech
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

tags:
  - name: group
    description: endpoints for group information
  - name: person
    description: endpoints for person information
  - name: system
    description: endpoints with system information
paths:
  /getGroupId:
    post:
      summary: Get a group id by group number
      requestBody:
        $ref: '#/components/requestBodies/GetGroupIdRequest'
      responses:
        '200':
          description: Found group id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGroupIdResponse'
        '400':
          description: Group id not found
        '500':
          description: Internal server error
      deprecated: true

  /getGroupSchedule:
    post:
      summary: Get a group schedule by group number
      requestBody:
        $ref: '#/components/requestBodies/GetScheduleByGroupRequest'
      responses:
        '200':
          description: Schedule for a group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        '400':
          description: Schedule not found
        '500':
          description: Internal server error
      deprecated: true

  /system/health:
    get:
      tags:
        - system
      summary: will check service is healthy or not
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /system/clearCache/{selector}/{secretKey}:
    delete:
      tags:
        - system
      summary: Only for internal use!
      responses:
        '200':
          description: Sucesfully cleared cache
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /v1/group/{groupNumber}/schedule/{offset}:
    get:
      tags:
        - group
      summary: GetScheduleByGroupNumber
      description: Get a schedule for group by group number
      parameters:
        - name: groupNumber
          in: path
          description: Number of a group
          required: true
          schema:
            type: string
            example: "А-08-20"
        - name: offset
          in: path
          description: Offset or range of offsets separated by a double dots. If you want to get the current week's schedule, pass offset equal to zero
          required: true
          schema:
            type: string
            example: "-1..1"
      responses:
        '200':
          description: Schedule for a group, for weeks specified in offset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleV1'
        '400':
          description: Schedule not found
        '500':
          description: Internal server error

  /v1/group/{groupNumber}/session:
    get:
      tags:
        - group
      summary: GetSessionByGroupNumber
      description: Get a session schedule for group by group number
      parameters:
        - name: groupNumber
          in: path
          description: number of a group
          required: true
          schema:
            type: string
            example: "А-08-20"
      responses:
        '200':
          description: Session schedule for a group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSessionResponseV1'
        '400':
          description: Session schedule not found
        '500':
          description: Internal server error

  /v1/person/{personName}/schedule/{offset}:
    get:
      tags:
        - person
      summary: GetScheduleByPersonName
      description: Get a person schedule for group by group number
      parameters:
        - name: personName
          in: path
          description: Person name
          required: true
          schema:
            type: string
            example: "Зуев Юрий Юрьевич"
        - name: offset
          in: path
          description: Offset or range of offsets separated by a double dots. If you want to get the current week's schedule, pass offset equal to zero
          required: true
          schema:
            type: string
            example: "-1..1"
      responses:
        '200':
          description: Schedule for a person, for weeks specified in offset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleV1'
        '400':
          description: Schedule not found
        '500':
          description: Internal server error

  /v1/person/{personName}/session:
    get:
      tags:
        - person
      summary: GetSessionByPersonName
      description: Get a person session schedule for group by group number
      parameters:
        - name: personName
          in: path
          description: Person name
          required: true
          schema:
            type: string
            example: "Зуев Юрий Юрьевич"
      responses:
        '200':
          description: Person session schedule for a group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSessionResponseV1'
        '400':
          description: Session schedule not found
        '500':
          description: Internal server error

  /v1/search:
    get:
      summary: SearchByQuery
      description: Get a suitable list for autocomplete query
      parameters:
        - in: query
          name: query
          schema:
            type: string
            example: "Зуев"
          description: Search query
        - in: query
          name: type
          schema:
            type: string
            example: "GROUP"
          description: Query filter
      responses:
        '200':
          description: Suitable list for autocomplete
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SearchByQueryResponseV1'
        '500':
          description: Internal server error

components:
  schemas:
    Time:
      type: object
      required: ["start", "end"]
      properties:
        start:
          type: string
          example: 00:00:00
          description: "LocalTime"
        end:
          type: string
          example: 04:20:00
          description: "LocalTime"

    Classes:
      type: object
      required:
        - name
        - type
        - place
        - groups
        - person
        - number
        - time
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - "UNDEFINED"
            - "LECTURE"
            - "PRACTICE"
            - "LAB"
            - "COURSE"
            - "EXAM"
            - "CONSULTATION"
        rawType:
          type: string
        place:
          type: string
        groups:
          type: string
        person:
          type: string
        number:
          type: integer
          format: int32
        time:
          $ref: "#/components/schemas/Time"

    Day:
      type: object
      required:
        - dayOfWeek
        - date
        - classes
      properties:
        dayOfWeek:
          type: integer
          format: int32
        date:
          type: string
          format: date
        classes:
          type: array
          items:
            $ref: "#/components/schemas/Classes"

    Week:
      type: object
      required:
        - weekOfYear
        - weekOfSemester
        - firstDayOfWeek
        - days
      properties:
        weekOfYear:
          type: integer
          format: int32
        weekOfSemester:
          type: integer
          format: int32
        firstDayOfWeek:
          type: string
          format: date
        days:
          type: array
          items:
            $ref: "#/components/schemas/Day"

    Schedule:
      type: object
      required:
        - groupNumber
        - groupId
        - weeks
      properties:
        groupNumber:
          type: string
        groupId:
          type: string
        weeks:
          type: array
          items:
            $ref: "#/components/schemas/Week"

    ScheduleV1:
      type: object
      required:
        - name
        - id
        - type
        - weeks
      properties:
        name:
          type: string
          description: group number or person name
        id:
          type: string
        type:
          type: string
          enum:
            - GROUP
            - PERSON
        weeks:
          type: array
          items:
            $ref: "#/components/schemas/Week"

    GetGroupIdResponse:
      type: object
      properties:
        groupNumber:
          type: string
          example: "А-01-16"
        groupId:
          type: string
          example: "9378"
    
    GetSessionResponseV1:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/SessionItemV1"

    SessionItemV1:
      type: object
      properties:
        name:
          type: string
        place:
          type: string
        person:
          type: string
        date:
          type: string
          format: date
        time:
          $ref: "#/components/schemas/Time"
        type:
          type: string
          enum:
            - "UNDEFINED"
            - "EXAM"
            - "CONSULTATION"
      
    SearchByQueryResponseV1:
      type: object
      required: ["items"]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/AutocompleteItemV1"

    AutocompleteItemV1:
      type: object
      required:
        - name
        - description
        - id
        - type
      properties:
        name:
          type: string
        description:
          type: string
        id:
          type: integer
          format: int32
        type:
          type: string
          enum:
            - "GROUP"
            - "PERSON"

  requestBodies:
    GetGroupIdRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              groupNumber:
                type: string
                example: "А-01-16"

    GetScheduleByGroupRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              groupNumber:
                type: string
                example: "А-01-16"
              weekOffset:
                type: integer
                format: int32
