openapi: 3.0.0
info:
  description: Mpeix microservice responsible for the schedule
  version: "1.0.0"
  title: Schedule
  contact:
    name: KekMech
    url: https://vk.com/kekmech
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

tags:
  - name: group
    description: endpoints for group information
  - name: person
    description: endpoints for person information
  - name: system
    description: endpoints with system information
paths:
  /getGroupId:
    post:
      summary: Get a group id by group number
      requestBody:
        $ref: '#/components/requestBodies/GetGroupIdRequest'
      responses:
        '200':
          description: Found group id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGroupIdResponse'
        '422':
          description: Group id not found
        '500':
          description: Internal server error
      deprecated: true

  /getGroupSchedule:
    post:
      summary: Get a group schedule by group number
      requestBody:
        $ref: '#/components/requestBodies/GetScheduleByGroupRequest'
      responses:
        '200':
          description: Schedule for a group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        '422':
          description: Schedule not found
        '500':
          description: Internal server error
      deprecated: true

  /system/health:
    get:
      tags:
        - system
      summary: will check service is healthy or not
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /v1/group/{groupNumber}/schedule/{offset}:
    get:
      tags:
        - group
      summary: GetScheduleByGroupNumber
      description: Get a schedule for group by group number
      parameters:
        - name: groupNumber
          in: path
          description: Number of a group
          required: true
          schema:
            type: string
            example: "А-08-20"
        - name: offset
          in: path
          description: Offset or range of offsets separated by a double dots. If you want to get the current week's schedule, pass offset equal to zero
          required: true
          schema:
            type: string
            example: "-1..1"
      responses:
        '200':
          description: Schedule for a group, for weeks specified in offset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleV1'
        '422':
          description: Schedule not found
        '500':
          description: Internal server error

  /v1/group/{groupNumber}/session:
    get:
      tags:
        - group
      summary: GetSessionByGroupNumber
      description: Get a session schedule for group by group number
      parameters:
        - name: groupNumber
          in: path
          description: number of a group
          required: true
          schema:
            type: string
            example: "А-08-20"
      responses:
        '200':
          description: Session schedule for a group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSessionResponseV1'
        '422':
          description: Session schedule not found
        '500':
          description: Internal server error

  /v1/person/{personName}/schedule/{offset}:
    get:
      tags:
        - person
      summary: GetScheduleByPersonName
      description: Get a person schedule for group by group number
      parameters:
        - name: personName
          in: path
          description: Person name
          required: true
          schema:
            type: string
            example: "Зуев Юрий Юрьевич"
        - name: offset
          in: path
          description: Offset or range of offsets separated by a double dots. If you want to get the current week's schedule, pass offset equal to zero
          required: true
          schema:
            type: string
            example: "-1..1"
      responses:
        '200':
          description: Schedule for a person, for weeks specified in offset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleV1'
        '422':
          description: Schedule not found
        '500':
          description: Internal server error

  /v1/person/{personName}/session:
    get:
      tags:
        - person
      summary: GetSessionByPersonName
      description: Get a person session schedule for group by group number
      parameters:
        - name: personName
          in: path
          description: Person name
          required: true
          schema:
            type: string
            example: "Зуев Юрий Юрьевич"
      responses:
        '200':
          description: Person session schedule for a group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSessionResponseV1'
        '422':
          description: Session schedule not found
        '500':
          description: Internal server error


components:
  schemas:
    Time:
      type: object
      properties:
        start:
          type: string
          example: 00:00:00
        end:
          type: string
          example: 04:20:00

    Classes:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - "UNDEFINED"
            - "LECTURE"
            - "PRACTICE"
            - "LAB"
            - "COURSE"
        place:
          type: string
        groups:
          type: string
        person:
          type: string
        number:
          type: integer
          format: int32
        time:
          $ref: "#/components/schemas/Time"

    ClassesV1:
      type: object
      properties:
        name:
          type: string
        typeName:
          type: string
        typeColor:
          type: string
        place:
          type: string
        groups:
          type: string
        person:
          type: string
        number:
          type: integer
          format: int32
        time:
          $ref: "#/components/schemas/Time"

    Day:
      type: object
      properties:
        dayOfWeek:
          type: integer
          format: int32
        date:
          type: string
          format: date
        classes:
          type: array
          items:
            $ref: "#/components/schemas/Classes"

    DayV1:
      type: object
      properties:
        dayOfWeek:
          type: integer
          format: int32
        date:
          type: string
          format: date
        classes:
          type: array
          items:
            $ref: "#/components/schemas/ClassesV1"

    Week:
      type: object
      properties:
        weekOfYear:
          type: integer
          format: int32
        weekOfSemester:
          type: integer
          format: int32
        firstDayOfWeek:
          type: string
          format: date
        days:
          type: array
          items:
            $ref: "#/components/schemas/Day"

    WeekV1:
      type: object
      properties:
        weekOfYear:
          type: integer
          format: int32
        weekOfSemester:
          type: integer
          format: int32
        firstDayOfWeek:
          type: string
          format: date
        days:
          type: array
          items:
            $ref: "#/components/schemas/DayV1"

    Schedule:
      type: object
      properties:
        groupNumber:
          type: string
        groupId:
          type: string
        weeks:
          type: array
          items:
            $ref: "#/components/schemas/Week"

    ScheduleV1:
      type: object
      properties:
        ownerName:
          type: string
          description: group number or person name
        groupId:
          type: string
        isPerson:
          type: boolean
        weeks:
          type: array
          items:
            $ref: "#/components/schemas/WeekV1"

    GetGroupIdResponse:
      type: object
      properties:
        groupNumber:
          type: string
          example: "А-01-16"
        groupId:
          type: string
          example: "9378"
    
    GetSessionResponseV1:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/SessionItemV1"

    SessionItemV1:
      type: object
      properties:
        name:
          type: string
        place:
          type: string
        person:
          type: string
        date:
          type: string
          format: date
        time:
          $ref: "#/components/schemas/Time"
        type:
          type: string
          enum:
            - "UNDEFINED"
            - "EXAM"
            - "CONSULTATION"

  requestBodies:
    GetGroupIdRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              groupNumber:
                type: string
                example: "А-01-16"

    GetScheduleByGroupRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              groupNumber:
                type: string
                example: "А-01-16"
              weekOffset:
                type: integer
                format: int32
